### ISSUE TITLE
DB: Denver SIDs & STARs dead links

### ISSUE THREAD

**Issue by Celeo** [adh-partnership/api#142]
Heya,

The links to airport charts from pages like <https://zdvartcc.org/airports/DEN> are dead links. Clicking "POWDR ONE" links to <https://aeronav.faa.gov/d-tpp/2304/09077POWDR.PDF>, when it should probably link to <https://aeronav.faa.gov/d-tpp/2307/09077POWDR.PDF>.

**Comment by dhawton** [comment]
Means your chart parser did not complete successfully on the day the cycles changed and you'll need to review the logs of the job to determine why.

**Comment by Celeo** [comment]
Looks good
