### ISSUE TITLE
Event Sanity Checks

### ISSUE THREAD

**Issue by Raajheer1** [adh-partnership/api#78]
On create Signup check for empty values for choice1, choice2, and choice3. Also check to see if user has a signup already, if so. Overwrite the old signup rather than creating duplicate signups for that user.

On create position check for null position name.

**Comment by dhawton** [comment]
choice1/2/3 should be able to be empty strings in case the user has no selection, ie they only want 1 position or none.

**Comment by dhawton** [comment]
the rest of this is fixed and merged.
