### ISSUE TITLE
Feedback praise

### ISSUE THREAD

**Issue by dhawton** [adh-partnership/api#84]
Only broadcast positive feedback when approved instead of all... maybe mask names on Fair/Poor ratings but still show as they could still prove to be good teaching points?

**Comment by austinwilkins1** [comment]
Wonder if we can allow manual praises (similar to now) for discord, which would allow us to approve negative feedback and not have the webhook automatically post it. 

Agree though, if negative or poor/fair is approved its generally good for teachable moments but not sure we would want that all going public, especially if its out of character but we still want it on the controllers record.

**Comment by dhawton** [comment]
Unfortunately the API is not designed a manual broadcast flag and that would be ZDV only feature... opted to only have to post Excellent/Good reviews automatically.
